# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
    - "hiltontj"
    commit-message:
      prefix: "chore"
    rebase-strategy: "disabled"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
    - "hiltontj"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "disabled"
      
